rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:delivery_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:ZSE444eszlightoton}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml